import './variables.css'
import './global.css'
import './fonts.css'
// import './utils.css'
// import './normalize.css'
import './components/intro.css'
import './components/header.css'
import './components/main.css'
import './components/animationMain.css'
import './components/portfolio.css'